ALTER TABLE user_event_types
MODIFY COLUMN user_event_types ENUM(
'ACCOUNT_CREATED', 'AD_WATCHED', 'CASE_STARTED', 'CASE_COMPLETED',
    'SUBSCRIPTIONS', 'LOGIN', 'LOGOUT', 'DELETE_ACCOUNT', 'CHANGE_PASSWORD',
    'FORGOT_PASSWORD', 'RESET_PASSWORD'
) NOT NULL;