package com.example.be.enums;

public enum UserEventType {

    ACCOUNT_CREATED,
    AD_WATCHED,
    CASE_STARTED,
    CASE_COMPLETED,
    SUBSCRIPTIONS,
    LOGIN,
    LOGOUT,
    DELETE_ACCOUNT,
    CHANGE_PASSWORD,
    FORGOT_PASSWORD,
    RESET_PASSWORD,
    HINT_USED,
    SQL_EXECUTED,
    ANSWER_FAILED
}